sudo: required
services:
        - docker
before_install:
        - docker build -t pbalacha/docker-react -f Dockerfile.dev .

script:
        - docker run pbalacha/docker-react npm run test -- --coverage
